release.yml - DENO_ROOT_PATH as global env

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -12,6 +12,9 @@ jobs:
   createRelease:
     runs-on: ubuntu-latest
 
+    env:
+      DENO_ROOT_PATH: ${{ env.RUNNER_TEMP }}/deno
+
     steps:
       - name: Check denoVersion
         run: |
@@ -38,8 +41,8 @@ jobs:
       - name: Clean TEMP
         run: echo === RUNNER_TEMP=$RUNNER_TEMP && rm -rf $RUNNER_TEMP && mkdir -p $RUNNER_TEMP
 
-      - name: Clean Workspace
-        run: echo === GITHUB_WORKSPACE=$GITHUB_WORKSPACE && rm -rf $GITHUB_WORKSPACE && mkdir -p $GITHUB_WORKSPACE
+      # - name: Clean Workspace
+      #   run: echo === GITHUB_WORKSPACE=$GITHUB_WORKSPACE && rm -rf $GITHUB_WORKSPACE && mkdir -p $GITHUB_WORKSPACE
 
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Checkout
@@ -67,14 +70,10 @@ jobs:
           rm -rf $DENO_ROOT_PATH && mkdir -p $DENO_ROOT_PATH
           echo Deno Linux
           bash $GITHUB_WORKSPACE/githubScripts/get-deno.sh $DENO_ROOT_PATH/linux Linux ${{ github.event.inputs.denoVersion }}
-        env:
-          DENO_ROOT_PATH: ${{ env.RUNNER_TEMP }}/deno
 
       - name: Check sources
         run: |
           bash $GITHUB_WORKSPACE/githubScripts/levain-check.sh $DENO_ROOT_PATH/linux/deno
-        env:
-          DENO_ROOT_PATH: ${{ env.RUNNER_TEMP }}/deno
 
       - name: Git config commit user
         run: |
@@ -97,7 +96,6 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           LEVAIN_VERSION: ${{ env.RELEASE_VERSION }} 
-          DENO_ROOT_PATH: ${{ env.RUNNER_TEMP }}/deno
 
       - name: Copy tagged version
         run: |
@@ -110,7 +108,6 @@ jobs:
         run: |
           bash $GITHUB_WORKSPACE/githubScripts/levain-compile.sh $DENO_ROOT_PATH/linux/deno $LEVAIN_RELEASE_SRC_PATH $LEVAIN_RELEASE_BIN_PATH 
         env:
-          DENO_ROOT_PATH: ${{ env.RUNNER_TEMP }}/deno
           LEVAIN_VERSION: ${{ env.RELEASE_VERSION }} 
           LEVAIN_RELEASE_SRC_PATH: ${{ env.RUNNER_TEMP }}/src/levain-${{ env.RELEASE_VERSION }}
           LEVAIN_RELEASE_BIN_PATH: ${{ env.RUNNER_TEMP }}/bin/levain-${{ env.RELEASE_VERSION }}
@@ -126,7 +123,6 @@ jobs:
         run: |
           bash $GITHUB_WORKSPACE/githubScripts/levain-embedded-binaries.sh $LEVAIN_RELEASE_BIN_PATH
         env:
-          DENO_ROOT_PATH: ${{ env.RUNNER_TEMP }}/deno
           LEVAIN_VERSION: ${{ env.RELEASE_VERSION }} 
           LEVAIN_RELEASE_BIN_PATH: ${{ env.RUNNER_TEMP }}/bin/levain-${{ env.RELEASE_VERSION }}
 
@@ -140,7 +136,6 @@ jobs:
         run: |
           bash $GITHUB_WORKSPACE/githubScripts/levain-bootstrap.sh $LEVAIN_RELEASE_SRC_PATH $RUNNER_TEMP/levainBootstrap-windows-x86_64.zip
         env:
-          DENO_ROOT_PATH: ${{ env.RUNNER_TEMP }}/deno
           LEVAIN_VERSION: ${{ env.RELEASE_VERSION }} 
           LEVAIN_RELEASE_SRC_PATH: ${{ env.RUNNER_TEMP }}/src/levain-${{ env.RELEASE_VERSION }}
 
@@ -164,6 +159,10 @@ jobs:
         env:
           LEVAIN_VERSION: ${{ env.RELEASE_VERSION }} 
           LEVAIN_RELEASE_BIN_PATH: ${{ env.RUNNER_TEMP }}/bin/levain-${{ env.RELEASE_VERSION }}
+
+
+      # - name: FAIL
+      #   run: exit 1
 
 
       ##############################################################
